//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class LidarScanMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/LidarScan";
        public override string RosMessageName => k_RosMessageName;

        //  LidarScan.msg
        //  Header with stamp & frame_id
        public Std.HeaderMsg header;
        //  Number of points in this scan
        public uint point_count;
        //  Flattened arrays of x, y, z coordinates
        public float[] x;
        public float[] y;
        public float[] z;

        public LidarScanMsg()
        {
            this.header = new Std.HeaderMsg();
            this.point_count = 0;
            this.x = new float[0];
            this.y = new float[0];
            this.z = new float[0];
        }

        public LidarScanMsg(Std.HeaderMsg header, uint point_count, float[] x, float[] y, float[] z)
        {
            this.header = header;
            this.point_count = point_count;
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public static LidarScanMsg Deserialize(MessageDeserializer deserializer) => new LidarScanMsg(deserializer);

        private LidarScanMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.point_count);
            deserializer.Read(out this.x, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.y, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.z, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.point_count);
            serializer.WriteLength(this.x);
            serializer.Write(this.x);
            serializer.WriteLength(this.y);
            serializer.Write(this.y);
            serializer.WriteLength(this.z);
            serializer.Write(this.z);
        }

        public override string ToString()
        {
            return "LidarScanMsg: " +
            "\nheader: " + header.ToString() +
            "\npoint_count: " + point_count.ToString() +
            "\nx: " + System.String.Join(", ", x.ToList()) +
            "\ny: " + System.String.Join(", ", y.ToList()) +
            "\nz: " + System.String.Join(", ", z.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
